"""added pokemon team lists

Revision ID: 01286fddda80
Revises: 1f8048b81d43
Create Date: 2026-09-27 20:17:27.038304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01286fddda80'
down_revision: Union[str, Sequence[str], None] = '1f8048b81d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pokemon_team', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{}'::integer[]"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pokemon_team')
    # ### end Alembic commands ###
